# Generated by Django 5.2.10 on 2026-01-12 17:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('GCS_max', models.FloatField(blank=True, null=True)),
                ('GCS_mean', models.FloatField(blank=True, null=True)),
                ('Lactate_min', models.FloatField(blank=True, null=True)),
                ('Lactate_max', models.FloatField(blank=True, null=True)),
                ('Lactate_mean', models.FloatField(blank=True, null=True)),
                ('BUN_min', models.FloatField(blank=True, null=True)),
                ('BUN_mean', models.FloatField(blank=True, null=True)),
                ('Bilirubin_max', models.FloatField(blank=True, null=True)),
                ('Bilirubin_mean', models.FloatField(blank=True, null=True)),
                ('AG_MEAN', models.FloatField(blank=True, null=True)),
                ('AG_MAX', models.FloatField(blank=True, null=True)),
                ('AG_MIN', models.FloatField(blank=True, null=True)),
                ('AG_STD', models.FloatField(blank=True, null=True)),
                ('SYSBP_MIN', models.FloatField(blank=True, null=True)),
                ('SYSBP_MEAN', models.FloatField(blank=True, null=True)),
                ('SYSBP_STD', models.FloatField(blank=True, null=True)),
                ('DIASBP_MIN', models.FloatField(blank=True, null=True)),
                ('DIASBP_MEAN', models.FloatField(blank=True, null=True)),
                ('AGE', models.FloatField(blank=True, null=True)),
                ('RR_MEAN', models.FloatField(blank=True, null=True)),
                ('RR_MAX', models.FloatField(blank=True, null=True)),
                ('RR_MIN', models.FloatField(blank=True, null=True)),
                ('TEMP_STD', models.FloatField(blank=True, null=True)),
                ('TEMP_MIN', models.FloatField(blank=True, null=True)),
                ('HR_MEAN', models.FloatField(blank=True, null=True)),
                ('HR_MAX', models.FloatField(blank=True, null=True)),
                ('HR_STD', models.FloatField(blank=True, null=True)),
                ('RDW_max', models.FloatField(blank=True, null=True)),
                ('RDW_mean', models.FloatField(blank=True, null=True)),
                ('RDW_min', models.FloatField(blank=True, null=True)),
                ('RDW_std', models.FloatField(blank=True, null=True)),
                ('age_adj_comorbidity_score', models.FloatField(blank=True, null=True)),
                ('MEANBP_MIN', models.FloatField(blank=True, null=True)),
                ('MEANBP_MEAN', models.FloatField(blank=True, null=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observation_sets', to='patients.encounter')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_observations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
