# Generated by Django 5.2.10 on 2026-01-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationset',
            name='recorded_by_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
