# Generated by Django 5.2.10 on 2026-01-13 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_observationset_recorded_by_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observationset',
            name='recorded_by_name',
        ),
    ]
