# Generated by Django 5.2.10 on 2026-01-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0004_observationset_recorded_by_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationset',
            name='recorded_by_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
