# Generated by Django 5.2.10 on 2026-01-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0005_alter_observationset_recorded_by_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observationset',
            old_name='AGE',
            new_name='Albumin_max',
        ),
        migrations.RenameField(
            model_name='observationset',
            old_name='DIASBP_MEAN',
            new_name='Albumin_mean',
        ),
        migrations.RenameField(
            model_name='observationset',
            old_name='DIASBP_MIN',
            new_name='Albumin_min',
        ),
        migrations.RenameField(
            model_name='observationset',
            old_name='HR_MAX',
            new_name='AlkPhos_max',
        ),
        migrations.RenameField(
            model_name='observationset',
            old_name='HR_MEAN',
            new_name='AlkPhos_mean',
        ),
        migrations.RenameField(
            model_name='observationset',
            old_name='HR_STD',
            new_name='AlkPhos_min',
        ),
        migrations.RenameField(
            model_name='observationset',
            old_name='MEANBP_MEAN',
            new_name='BUN_max',
        ),
        migrations.RenameField(
            model_name='observationset',
            old_name='MEANBP_MIN',
            new_name='DIASBP_mean',
        ),
        migrations.RenameField(
            model_name='observationset',
            old_name='RR_MAX',
            new_name='DIASBP_min',
        ),
        migrations.RenameField(
            model_name='observationset',
            old_name='RR_MEAN',
            new_name='HR_max',
        ),
        migrations.RenameField(
            model_name='observationset',
            old_name='RR_MIN',
            new_name='HR_mean',
        ),
        migrations.RenameField(
            model_name='observationset',
            old_name='SYSBP_MEAN',
            new_name='HR_std',
        ),
        migrations.RenameField(
            model_name='observationset',
            old_name='SYSBP_MIN',
            new_name='INR_mean',
        ),
        migrations.RenameField(
            model_name='observationset',
            old_name='SYSBP_STD',
            new_name='INR_min',
        ),
        migrations.RenameField(
            model_name='observationset',
            old_name='TEMP_MIN',
            new_name='MEANBP_mean',
        ),
        migrations.RenameField(
            model_name='observationset',
            old_name='TEMP_STD',
            new_name='MEANBP_min',
        ),
        migrations.AddField(
            model_name='observationset',
            name='PT_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observationset',
            name='PT_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observationset',
            name='PaO2_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observationset',
            name='PaO2_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observationset',
            name='Phosphate_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observationset',
            name='Phosphate_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observationset',
            name='RR_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observationset',
            name='RR_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observationset',
            name='RR_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observationset',
            name='SYSBP_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observationset',
            name='SYSBP_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observationset',
            name='SYSBP_std',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observationset',
            name='TEMP_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observationset',
            name='TEMP_std',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observationset',
            name='aPTT_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observationset',
            name='aPTT_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observationset',
            name='age',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
