# Generated by Django 5.2.10 on 2026-01-16 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0006_rename_age_observationset_albumin_max_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observationset',
            old_name='AG_MEAN',
            new_name='AG_mean',
        ),
        migrations.RenameField(
            model_name='observationset',
            old_name='AG_MIN',
            new_name='AG_min',
        ),
        migrations.RenameField(
            model_name='observationset',
            old_name='AG_STD',
            new_name='AG_std',
        ),
    ]
