# Generated by Django 5.2.10 on 2026-01-16 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0007_rename_ag_mean_observationset_ag_mean_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observationset',
            old_name='AG_MAX',
            new_name='AG_max',
        ),
    ]
