# Generated by Django 5.2.10 on 2026-01-12 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='doctor_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_assessments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='model_version',
            field=models.CharField(default='', max_length=64),
        ),
    ]
