# Generated by Django 5.2.10 on 2026-01-12 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
        ('risk', '0002_riskassessment_doctor_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassessment',
            name='observation_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='observations.observationset'),
        ),
    ]
