# Generated by Django 5.2.10 on 2026-01-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0003_alter_riskassessment_observation_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='doctor_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
