# Generated by Django 5.2.10 on 2026-01-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0004_riskassessment_doctor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassessment',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
