# Generated by Django 5.2.10 on 2026-01-12 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=64)),
                ('object_type', models.CharField(max_length=128)),
                ('object_id', models.CharField(max_length=64)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='audit_audit_created_7710b7_idx'), models.Index(fields=['action'], name='audit_audit_action_203f66_idx'), models.Index(fields=['object_type', 'object_id'], name='audit_audit_object__0e78a5_idx')],
            },
        ),
    ]
